### ISSUE TITLE
Character status page: indicating lichness

### ISSUE THREAD

**Issue by rubyFeedback** [LCA-EET/Lichdom#10]
Is it being described somewhere that the character is now a lich? Not sure how easy it would be to add it, but I think it would be nice if we could get some text indicating that someone is now a lich.

Something like a substring in a listing:

"- Lich"

Or so... not sure where to fit this in, perhaps at the main character overview.

**Comment by LCA-EET** [comment]
Yes, the character information window will correctly reflect the race as Lich, once the transformation is completed.
