### ISSUE TITLE
Extra Lich Dusts?

### ISSUE THREAD

**Issue by rubyFeedback** [LCA-EET/Lichdom#11]
Right now I have four lich dusts. (By the way, is the enemy in Lava's mod from the observatory, aka The Incomplete, a lich? Perhaps not, but if he is I think he does not drop a lich dust upon destruction. Just mentioning this.)

Three are need for lich transformation. What to do with the fourth one?

If it is not needed, perhaps the item could be used to help forge some weapon or so. Like a weapon with imbued cold effect. Does not have to be too overly strong, I think a +2 or +3 weapon may suffice. Or another item that could be used for a lich effect or so. If there is no use case for the additional lich dusts then I guess I can just sell it.

**Comment by Endarire** [comment]
I added this to the Q & A section.

The intent was for players to sell or drop the spares - or keep them as trophies.

If you want to make a mod that uses Lichdom Lich Dusts for something, the license permits it and I encourage it!

Thankee!
