### ISSUE TITLE
[Possible small bug] Shroud of the Lich item (cloak)

### ISSUE THREAD

**Issue by rubyFeedback** [LCA-EET/Lichdom#12]
Viconia became lich (nobody else was available in the choice, perhaps that is a separate
bug). Oddly enough, the shroud of the lich item, the cloak, where the wearer (the lich)
is revived automatically, was given into the inventory of the main character - and it is
not removable. This is a bit annoying.

But, putting it into the main actor's inventory is wrong, in my opinion. Viconia should
carry it, similar to Hexxat carrying her cloak. So in pseudocode:

    if character.is_the_lich?
      cloak.move(to: character)

**Comment by LCA-EET** [comment]
Yes, you are correct. The shroud should belong to Viconia, not the main player. I'll take a look and post a new build tomorrow.

**Comment by LCA-EET** [comment]
I was not able to reproduce this issue in either the current or prior releases. If it happens again, open a new issue and include a copy of your save game.
