### ISSUE TITLE
[Possible inconsistency - or lacking explanation] I killed Morris

### ISSUE THREAD

**Issue by rubyFeedback** [LCA-EET/Lichdom#13]
So it is possible to kill Morris. I tried it in the SoA chapter, curious to find out what happens.

I may file another issue request, but for this one here, Morris, after having been killed, appears
in ToB just fine.

The question is: did Morris get ressed?

I am fine either way - that is, he is perma-deathed (if killed in SoA), or he gets ressed (for ToB).
But I believe that, IF he was killed in SoA, and then re-appears in ToB, some kind of explanation
should be added.

There are a few possibilities for this.

I think the simplest one is to add an additional talk-option in ToB that explains this, such as:

"Wait a moment ... didn't you ... uhm ... die in Athkatla?"

That is, the main character points to the death of Morris (not revealing that it was his own
party that murdered him).

Then Morris may say that, as a necromancer, he has found ways to defy death every now and
then. Something like that.

This would be the simpler solution I think.

Another simple solution is to perhaps add a post-death message, such as:

"As Morris dies, a very faint chilling voice can be heard ... I'll be back."

(Or something like that.)

The rationale here would be to explain why Morris is back. Right now there is
no real way of knowing why Morris is back again.

**Comment by LCA-EET** [comment]
Morris appearing in ToB after being killed in SoA was a creative decision by Endarire.

**Comment by Endarire** [comment]
Morris is a Lich with an off-site phylactery.
