### ISSUE TITLE
Killing Morris

### ISSUE THREAD

**Issue by rubyFeedback** [LCA-EET/Lichdom#14]
So I killed Morris.

I found a few oddities here.

First, I got the money back from his corpse that I paid for lichdom (Viconia actually).

Now, this makes sense because the money was handed over, but ... if we can get 
back the money, it becomes a zero cost situation. I don't think this was intended,
right?

It may be better to add some routine after Morris gets the money, aka some
animation part, where Morris puts the money into some bag and teleports
the bag away. Something like that.

This is not the only oddity though.

Morris had strange things in his corpse.

For one, it seems as if something cloned the inventory of the main character.
So I ended up with many magical items twice (!). Including the staff of magi
that makes the wearer invisible. This was in a bag of holding on his corpse.

It seemed as if something copied (cloned) some of the inventory of the main
character, but only some. Very confusing.

Morris also has had other things in his corpse. Perhaps someone could have
a look at what checks are made to determine what he has in his inventory.
Some things should probably not be there.

Also, I think a dedicated extra crypt in the graveyard with a fancy sarcophagus
would be nice - a bit similar to how Lava's Barovia mod added a new small
entry area there at the graveyard. That way Morris could have his own dedicated
hideout rather than be in the open. Anyway, this issue is primarily about the
oddity of killing Morris and having him have strange things in his inventory.

**Comment by LCA-EET** [comment]
Good point about the bag of holding. I believe I used the same bag of holding you find elsewhere in the game, so if the player has already acquired that bag, the player's items will be in Morris' bag as well. I'll make a new bag specifically for Morris, and delete the gold that he takes from the player.

**Comment by LCA-EET** [comment]
The bag of holding issue was corrected in the 1.1 release, and gold is destroyed once it is handed over to Morris.
