### ISSUE TITLE
Morris defence

### ISSUE THREAD

**Issue by rubyFeedback** [LCA-EET/Lichdom#16]
So, this is not a very important suggestion. Nonetheless in the event you feel like it, I
would like to suggest this.

Today I have installed the latest lichdom mod but haven't played it yet. I'll report any
findings from that, e. g. testing whether the bag bug is gone. In the process I'll have
to ... dispose of Morris. :)

Now, the mod leaves it kind of open whether Morris is a lich or not; I assume he is not,
at best he is aspiring to become one one day. But I also remember he was fairly
weak when I attacked him. Granted, my party was already overpowered at that point
due to many mods, but still, Morris gave little resistance.

I thus shall make a few suggestions - the aim is NOT to make Morris overpowered, but
to prevent insta-death for him.

1) First I would like to suggest he has some trigger; most mages have that e. g. 
casting stoneskin and shadow door and such. I'd suggest that Morris also gets 
such a trigger, at the least for stoneskin. This should not be too hard to implement
as I guess most wizards in the game that are attacked, if they are of a high level,
will have such a trigger.

Perhaps also mirror image or so.

2) Morris could also use area damage as defence then; perhaps cloudkill or something
like that.

3) If Morris is not a lich then perhaps he has a few bodyguards. These could be undead,
or just semi-undead (the grimlock archers) or hired humanoid warriors that could hide
nearby or so (he has to pay their salary of course, to ensure they are nearby; undead
bodyguards may make more sense, but I am not sure whether Morris is undead or not).

Alternatively it could be some golem or so. This could be from a one-use ring or so
that summons stone golems or clay golems or something.

4) Another perhaps simpler solution may be for Morris to drink a potion that increases
resistances; and to perhaps attempt to run away or hide nearby. Not sure if the latter
isn't too much effort to write code for, so I am not really suggesting it, but just mentioning
it.

I think probably 1) isn't too difficult to add, and perhaps a one-use summonable such as
golems or whatever else you think, may also be ok-ish. The idea is not to make Morris
a very hard to beat opponent (Tactics remix already has lots of such challenges), but
the idea is to make him a little bit more durable than getting insta-killed. Although, with
gold no longer being attained from his corpse, I guess players have less of a need to
kill him in the first place now. :D

**Comment by Endarire** [comment]
I haven't fought Morris in-game, but I assumed he had notable defenses like a caster of his stature would.

Recalling my time with SCS, many similar casters had Stoneskin, Mirror Image, Blur, Haste, Shield, Protection from Magic Weapons, Protection from Magic Energy, Spell Turning, Fire Shield (blue & red), Simulacrum, Globe of Invulnerability, and Animate Dead (Skeleton Warrior) x5.

@LCA-EET: I thought I included a buff script for him.  Apologies if I didn't.

If he's coded a Wizard specialized in Necromancy, you can ignore the Illusion spells..  Otherwise, include them.  Remember, his goal if attacked is to survive.  May we get this added in a near term release?

I'm also taking suggestions for how else to buff him.

Thankee!

**Comment by LCA-EET** [comment]
His combat script includes buffing, but it seems the sequencing is wrong. I'll post an updated version later today.

UPDATE: per the suggested implementation document, he just leaves if attacked in Athkatla. He only fights back in Saradush.

**Comment by LCA-EET** [comment]
Fixed in v1.1a. Thanks for reporting the issue.
