### ISSUE TITLE
Request: Crown of the Lich Turn Undead Immunity Option

### ISSUE THREAD

**Issue by Endarire** [LCA-EET/Lichdom#22]
Greetings, @LCA-EET!

I recently realized that foes tend not to use Turn/Rebuke Undead and immunity to this on the Crown of the Lich is mostly for player sanity.  May we get an install option for this?

Thankee!

**Comment by LCA-EET** [comment]
What should the default be? Immunity to Turn / Rebuke Undead, or no immunity? Thanks.

**Comment by Endarire** [comment]
No immunity for the sake of convenience.  I don't know off-hand of any AI foes that use Turn or Rebuke Undead, even with SCS.

**Comment by LCA-EET** [comment]
Added to version 1.31
