### ISSUE TITLE
Small typo in the main README

### ISSUE THREAD

**Issue by rubyFeedback** [LCA-EET/Lichdom#4]
"Installing most mods after EET End is a bad idea that an corrupt your game or otherwise produce undesirable effects!"

I believe a 'c' is missing, so it should be:

"Installing most mods after EET End is a bad idea that can corrupt your game or otherwise produce undesirable effects!"

Hope you don't mind small typo reports. :)

**Comment by Endarire** [comment]
Fixed.  Thankee!

PS: You're in the credit for your contributions.
