### ISSUE TITLE
"BEGIN XALDGD2 when XALDGD2 is already loaded/created" leading to some failure

### ISSUE THREAD

**Issue by rubyFeedback** [LCA-EET/Lichdom#7]
So the cross-mod stuff in regards to skitia was fixed, and the installation proceeded.

However had, I ran into another issue. First I will copy/paste it via four space indent:

    Compiling 1 dialogue file ...

    Skitia NPC mod detected. Updating dialogs accordingly...
    Compiling 1 dialogue file ...

    Skitia NPC mod detected. Updating dialogs accordingly...
    Compiling 1 dialogue file ...

    Saradas Magic NPC mod detected. Updating dialogs accordingly...
    Compiling 1 dialogue file ...

    Processing Throne of Bhaal changes...
    Compiling 3 dialogue files ...
    BEGIN XALDGD2 when XALDGD2 is already loaded/created
    (you should say BEGIN XALDGD2 exactly once and before APPEND XALDGD2, etc.)
    ERROR: preprocessing CREATE [tb#_compile_eval_buffer/LICHDOM/tob/d/xaldgd.d]: Failure("invalid D file")
    Stopping installation because of error.
    Stopping installation because of error.
    Stopping installation because of error.
    Stopping installation because of error.

    ERROR Installing [Lichdom for the Baldur's Gate, Enhanced Edition Games.], rolling back to previous state
    Will uninstall 1558 files for [LICHDOM/LICHDOM.TP2] component 0.
    Uninstalled    1558 files for [LICHDOM/LICHDOM.TP2] component 0.
    ERROR: Failure("invalid D file")

    Please make a backup of the file: SETUP-LICHDOM.DEBUG and look for support at: Daniel Valle, dan@danielvalle.net
    Using Language [English]

    Install Component [Lichdom for the Baldur's Gate, Enhanced Edition Games.]?
    [I]nstall, or [N]ot Install or [Q]uit?

(By the way, minor cosmetic stuff I think - skitia NPC mod is mentioned twice, but I
guess that is irrelevant thus cosmetic.)

Not quite sure about the error; probably the  "BEGIN XALDGD2 when XALDGD2" part
may need some tweaking. I really need to learn that language ... 

Anyway, that's it for me for today. For this run I'll make a weak party, for some challenge,
and try to finish the Never Winter Night mod (almost had it last time, but I ran into a 
graphics glitch). After that, probably with some days rest in between, I'll give Lich mod
another run as priority. Jan really needs to become a lich - and scare the kids ... (HOW EVIL).
(Actually, for a first run, I'll probably have the main actor be a lich, just to test it, as well as
the 40k gold, for easy mode play through. :D)

**Comment by LCA-EET** [comment]
When you extract the archive, first ensure that the existing Lichdom folder has been deleted. An older version of the installer included a copy of XALDGD2.D, which included a BEGIN ~XALDGD2~ statement. Newer versions of the installer move this statement to another file, but because Weidu detects the old file, it attempts to compile it which results in the error.

**Comment by LCA-EET** [comment]
See earlier comment - the fix is to delete the existing Lichdom directory before extracting the new installation archive.

**Comment by LCA-EET** [comment]
See earlier comment - the fix is to delete the existing Lichdom directory before extracting the new installation archive.
